### ISSUE TITLE
Sector Summaries

### ISSUE THREAD

**Issue by OnAGravitasHunt** [to-boldly-go/tbg-deployment-planner#14]
In addition to D<sub>tot</sub>/D<sub>req</sub>:
- [x] S,P (C?) totals
- [x] Summary of starships present
  - e.g. 1 Starbase, 1 *Excelsior*-A, 2 *Centaur*-B
- [x] Allow sector to be collapsed to just summary

**Comment by synchronizedwritersblock** [comment]
For task force deployments, war-time/emergency deployments, and non-D assignments, we often require full ship stats and "sector" (task force / front) stat totals, in an at-a-glance format. All totals rather than just SPD would be nice.

**Comment by synchronizedwritersblock** [comment]
Necessary sector information:
Type (internal, border zone, task force, theatre, fleet, etc.)
Supported By (list of mutual support BZs and theatres)
Theatre or Location (could potentially be part of the previous)
Ship stat totals, some containers will have non-D requirements too
Sector-specific bonuses
Major world count / Home world count
List of notable stats (mostly for task forces and emergencies, likely best in text note format rather than a selectable set because non-stat things can matter)

Not all of the above needs to be on the main page interface but it's all deployment-relevant information in the click-through.

**Comment by OnAGravitasHunt** [comment]
I've added these to your issue #18 because that's more where the functionality belongs

**Comment by OnAGravitasHunt** [comment]
Sector summaries (i.e. data visible on main page) done
